Edit and use for generate the 2nd version grammar archive 0507

In [40]:
import numpy as np

def renew19(line):
    tokens = line.split()
    newtokens = [x for x in tokens[:-1]]
    newtokens[0] = tokens[16]
    newtokens[1:3] = ['A', 'as']
    newtokens[3:5] = tokens[4:6]
    newtokens[5:9] = tokens[0:4]
    newtokens[9:12] = ['and', 'B', 'as']
    #newtokens[12:14] = tokens[12:14]
    newtokens[14:] = tokens[8:12]
    
    if newtokens[0] == 'mean':
        newtokens[0] = 'avg'
    newline = ' '.join(newtokens)
    return newline

def renew15(line):
    tokens = line.split()
    newtokens = [x for x in tokens[:-1]]
    newtokens[0:3] = tokens[12:]
    newtokens[3:7] = tokens[8:12]
    newtokens[7] = 'as'
    newtokens[8:10] = tokens[4:6]
    newtokens[10:] = tokens[0:4]
    newline = ' '.join(newtokens)
    return newline

def renew14(line):
    tokens = line.split()
    newtokens = [x for x in tokens[:-1]]
    newtokens[0:2] = tokens[12:]
    newtokens[2:6] = tokens[8:12]
    newtokens[6] = 'as'
    newtokens[7:9] = tokens[4:6]
    newtokens[9:] = tokens[0:4]
    newline = ' '.join(newtokens)
    return newline

def renew13(line):
    tokens = line.split()
    newtokens = [x for x in tokens[:-1]]
    newtokens[0] = tokens[10]
    newtokens[1:3] = ['A', 'as']
    newtokens[3:6] = tokens[0:3]
    newtokens[6:9] = ['and','B', 'as']
    newtokens[9:] = tokens[5:8]
    newline = ' '.join(newtokens)
    return newline

def renew11(line):
    tokens = line.split()
    newtokens = [x for x in tokens]
    newtokens[0:3] = tokens[8:]
    newtokens[3:7] = tokens[0:4]
    newtokens[7] = 'and'
    newtokens[8:] = tokens[5:8]
    newline = ' '.join(newtokens)
    return newline

def renew10(line):
    tokens = line.split()
    newtokens = [x for x in tokens]
    newtokens[0:2] = tokens[8:]
    newtokens[2:6] = tokens[0:4]
    newtokens[6] = 'and'
    newtokens[7:] = tokens[5:8]
    newline = ' '.join(newtokens)
    return newline

def renew7(line):
    tokens = line.split()
    newtokens = [x for x in tokens]
    newtokens[0:3] = tokens[4:]
    newtokens[3:] = tokens[0:4]
    newline = ' '.join(newtokens)
    return newline

def renew6(line):
    tokens = line.split()
    newtokens = [x for x in tokens]
    newtokens[0:2] = tokens[4:]
    newtokens[2:] = tokens[0:4]
    
    if newtokens[0] == 'mean':
        newtokens[0] = 'avg'
    newline = ' '.join(newtokens)
    return newline

def renew5(line):
    tokens = line.split()
    newtokens = [x for x in tokens]
    newtokens[0] = 'count'
    newtokens[1:] = tokens[0:4]
    newline = ' '.join(newtokens)
    return newline

len_search = dict()
f2 = open('./rand_test2.lo','w')
with open('./rand_test.lo') as f:
    for line in f:
        tokens = line.split()
        length = len(tokens)
        if length not in len_search:
            len_search[length] = []
        len_search[length].append(line)
        if length == 19:
            newline = renew19(line)
            f2.write(newline+'\n')
        elif length == 15:
            newline = renew15(line)
            f2.write(newline+'\n')
        elif length == 14:
            newline = renew14(line)
            f2.write(newline+'\n')
        elif length == 13:
            newline = renew13(line)
            f2.write(newline+'\n')
        elif length == 11:
            newline = renew11(line)
            f2.write(newline+'\n')
        elif length == 10:
            newline = renew10(line)
            f2.write(newline+'\n')
        elif length == 7:
            newline = renew7(line)
            f2.write(newline+'\n')
        elif length == 6:
            newline = renew6(line)
            f2.write(newline+'\n')
        elif length == 5:
            newline = renew5(line)
            f2.write(newline+'\n')
        else:
            f2.write(line)
f2.close()

for key in len_search.keys():
    value = len_search[key]
    print 'length = %d, total examples: %d' %(key, len(value))

length = 3, total examples: 21
length = 5, total examples: 13
length = 6, total examples: 148
length = 7, total examples: 78
length = 10, total examples: 86
length = 11, total examples: 65
length = 13, total examples: 1
length = 14, total examples: 1
length = 15, total examples: 23
length = 19, total examples: 75

In [42]:
len_search2 = dict()
with open('./rand_train.lo') as f2:
    for line in f2:
        tokens = line.split()
        length = len(tokens)
        if length not in len_search2:
            len_search2[length] = []
        len_search2[length].append(line)
for key in len_search2.keys():
    value = len_search2[key]
    print 'length = %d, total examples: %d' %(key, len(value))
    
for line in len_search2[15]:
    print line

length = 2, total examples: 1
length = 3, total examples: 111
length = 5, total examples: 99
length = 6, total examples: 739
length = 7, total examples: 446
length = 10, total examples: 490
length = 11, total examples: 351
length = 13, total examples: 3
length = 14, total examples: 6
length = 15, total examples: 109
length = 19, total examples: 445
where Swara equal Shadja select Position as A where Position less A argmax Swara Position

where Team equal Fingal_Ravens select Years as A where Years less A argmax Team Year

where State equal Bihar select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where Nation equal England select Rank as A where Rank less A argmax Nation Rank

where State equal Goa select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where Nation equal Netherlands select Rank as A where Rank less A argmax Nation Rank

where Team equal Maynooth select Years as A where Years less A argmax Team Year

where Team equal Maynooth select Years as A where Years greater A argmin Team Year

where State equal Assam select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly less A argmin State No._of_candidates

where State equal Himachal_Pradesh select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where State equal Meghalaya select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where Nation equal Italy select Rank as A where Rank less A argmin Nation Rank

where State equal Chhattisgarh select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly less A argmin State No._of_candidates

where Nation equal Wales select Rank as A where Rank less A argmax Nation Rank

where State equal Karnataka select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where State equal Tamil_Nadu select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where Nation equal Spain select Rank as A where Rank less A argmax Nation Rank

where State equal Jammu_and_Kashmir select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where State equal Gujarat select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly less A argmin State No._of_candidates

where State equal Tripura select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly less A argmin State No._of_candidates

where Swara equal Antara_Gandhara select Position as A where Position less A argmax Swara Position

where State equal Manipur select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where Nation equal Australia select Rank as A where Rank less A argmax Nation Rank

where State equal Assam select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where State equal Uttarakhand select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where Nation equal Japan select Rank as A where Rank greater A argmin Nation Rank

where State equal Bihar select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where State equal Chhattisgarh select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where State equal Rajasthan select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where State equal Gujarat select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where State equal Manipur select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly less A argmin State No._of_candidates

where Swara equal Shatshruti_Dhaivata select Position as A where Position less A argmax Swara Position

where State equal Rajasthan select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly less A argmin State No._of_candidates

where State equal Mizoram select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where State equal Assam select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where Nation equal Netherlands select Rank as A where Rank less A argmin Nation Rank

where Team equal Wolfe_Tones select Years as A where Years less A argmax Team Year

where State equal Mizoram select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly less A argmin State No._of_candidates

where Nation equal Mexico select Rank as A where Rank less A argmin Nation Rank

where Nation equal Wales select Rank as A where Rank less A argmin Nation Rank

where Nation equal Nepal select Rank as A where Rank less A argmax Nation Rank

where State equal Madhya_Pradesh select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where Swara equal Panchama select Position as A where Position less A argmax Swara Position

where Nation equal England select Rank as A where Rank less A argmin Nation Rank

where Nation equal Algeria select Rank as A where Rank less A argmax Nation Rank

where State equal Manipur select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where Swara equal Panchama select Position as A where Position greater A argmin Swara Position

where Swara equal Panchama select Position as A where Position greater A argmin Swara Position

where State equal Delhi select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where Swara equal Shadja select Position as A where Position greater A argmin Swara Position

where State equal West_Bengal select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where Nation equal Romania select Rank as A where Rank less A argmax Nation Rank

where State equal Meghalaya select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where Team equal Fingal_Ravens select Years as A where Years less A argmax Team Year

where State equal Mizoram select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where State equal Kerala select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where State equal Gujarat select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where State equal Rajasthan select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where State equal Uttarakhand select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly less A argmin State No._of_candidates

where State equal Maharashtra select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly less A argmin State No._of_candidates

where Nation equal Spain select Rank as A where Rank less A argmin Nation Rank

where Team equal Ballyroan_Abbey select Years as A where Years less A argmax Team Year

where Team equal Fingal_Ravens select Years as A where Years less A argmax Team Year

where State equal Maharashtra select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where State equal Tripura select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where State equal Uttarakhand select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where Team equal Ballyroan_Abbey select Years as A where Years less A argmax Team Year

where State equal Karnataka select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly less A argmin State No._of_candidates

where State equal Chhattisgarh select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where State equal Delhi select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly less A argmin State No._of_candidates

where State equal Tripura select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where State equal Punjab select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where Team equal Maynooth select Years as A where Years greater A argmin Team Year

where State equal Jammu_and_Kashmir select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where State equal Himachal_Pradesh select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly less A argmin State No._of_candidates

where Swara equal Antara_Gandhara select Position as A where Position greater A argmin Swara Position

where State equal Puducherry select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly less A argmin State No._of_candidates

where Nation equal Nepal select Rank as A where Rank greater A argmin Nation Rank

where State equal Uttar_Pradesh select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where State equal Puducherry select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where State equal Odisha select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where State equal Tamil_Nadu select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where Nation equal China select Rank as A where Rank less A argmax Nation Rank

where State equal Madhya_Pradesh select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where Swara equal Shatshruti_Dhaivata select Position as A where Position greater A argmin Swara Position

where Nation equal France select Rank as A where Rank greater A argmin Nation Rank

where State equal Goa select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where State equal West_Bengal select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where State equal Andhra_Pradesh select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where State equal Odisha select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where State equal Punjab select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where Nation equal France select Rank as A where Rank less A argmax Nation Rank

where Team equal Wolfe_Tones select Years as A where Years greater A argmin Team Year

where State equal West_Bengal select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly less A argmin State No._of_candidates

where Swara equal Shadja select Position as A where Position greater A argmin Swara Position

where Team equal Fingal_Ravens select Years as A where Years greater A argmin Team Year

where State equal Bihar select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly less A argmin State No._of_candidates

where Nation equal Romania select Rank as A where Rank less A argmin Nation Rank

where Nation equal Mexico select Rank as A where Rank less A argmax Nation Rank

where State equal Haryana select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where State equal Punjab select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where State equal Uttar_Pradesh select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly less A argmin State No._of_candidates

where Nation equal Brazil select Rank as A where Rank less A argmin Nation Rank

where Swara equal Shatshruti_Dhaivata select Position as A where Position greater A argmin Swara Position

where State equal Karnataka select No._of_candidates as A where No._of_candidates less A argmax State No._of_elected

where State equal Andhra_Pradesh select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly greater A argmax State No._of_candidates

where Team equal Ballyroan_Abbey select Years as A where Years less A argmax Team Year

where State equal Punjab select Total_no._of_seats_in_Assembly as A where Total_no._of_seats_in_Assembly less A argmin State No._of_candidates

where Team equal Fingal_Ravens select Years as A where Years greater A argmin Team Year